### ISSUE TITLE
Some questions about evaluation?

### ISSUE THREAD

**Issue by Ko-vey** [RicherMans/PSL#1]
Hello! I am trying to obtain teacher model from this project recently. After some modification, I finally made it trained and obtained 4 checkpoint models from psl_balanced_chunk_10sec and teacher_student_chunk_5sec respectively, but there are some questions I am not sure:
1. 
After training, how to perform "evaluate" part for my trained model exactly?
I tried to modify evaluate function like:
`
def evaluate(
self,
experiment_path: Path = '../src/experiments/psl_balanced_chunk_10sec/MobileNetV2_DM_MobileNetV2_DM/2022-05-27_16-01-05_2cd778a6dd9311ec98a1d542cc97d3a1',
test_data_file: Path = '../data/labels/eval.csv',
label_indices: Path = '../data/csvs/class_labels_indices.csv',
num_classes=527,
**kwargs,
):
`
but raised an error:
`
ssh: .../envs/PSL4/bin/python3.7 -u .../myProjects/PSL/src/run.py evaluate ../configs/psl_balanced_chunk_10sec.yaml
[2022-05-28 17:41:06] Using seed 42
Traceback (most recent call last):
  File ".../myProjects/PSL/src/run.py", line 468, in <module>
    Fire(Runner)
  File ".../envs/PSL4/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File ".../envs/PSL4/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File ".../envs/PSL4/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File ".../myProjects/PSL/src/run.py", line 388, in evaluate
    training_dump = torch.load(experiment_path, map_location='cpu')
  File ".../envs/PSL4/lib/python3.7/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File ".../envs/PSL4/lib/python3.7/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK

Process finished with exit code 1
`
What should I do to make it work?
2.
What are the models I have obtained from training? Are they just student models?

**Comment by RicherMans** [comment]
> I tried to modify evaluate function like:
def evaluate( self, experiment_path: Path = '../src/experiments/psl_balanced_chunk_10sec/MobileNetV2_DM_MobileNetV2_DM/2022-05-27_16-01-05_2cd778a6dd9311ec98a1d542cc97d3a1', test_data_file: Path = '../data/labels/eval.csv', label_indices: Path = '../data/csvs/class_labels_indices.csv', num_classes=527, **kwargs, ):
but raised an error:

So first of all, I never recommend to actually modify any source code in order to i.e., simply change some input parameters of a script, It's just bad design and super error prone. I recommend to use the --experiment_path YOURPATH version of the script.

The error you get is just simply a problem with the IO, i.e., maybe it opened a file with torch.load() which is not a torch file.
I recommend to simply pass the full path to the evaluate script such as:

```bash
python3 run.py evaluate ../src/experiments/psl_balanced_chunk_10sec/MobileNetV2_DM_MobileNetV2_DM/2022-05-27_16-01-05_2cd778a6dd9311ec98a1d542cc97d3a1/YOURBEST_CHECKPOINT.pt
```

> 2. What are the models I have obtained from training? Are they just student models?

Sure they are students, teacher is fixed in all experiments.

**Comment by Ko-vey** [comment]
> Sure they are students, teacher is fixed in all experiments.

I'm sorry but, you mentioned that teacher model can be trained via PSL by replacing with CDur or other CRNN based model in [Datadriven-GPVAD](https://github.com/RicherMans/Datadriven-GPVAD/issues/8), but teacher is fixed here?

Also, I tried to process single audio file with ./src/forward.py, which returned event label and probability. Is it applicable to output frame-level prediction and time period for each sound event?
Thank you!

**Comment by RicherMans** [comment]
> I'm sorry but, you mentioned that teacher model can be trained via PSL by replacing with CDur or other CRNN based model in https://github.com/RicherMans/Datadriven-GPVAD/issues/8, but teacher is fixed here?

I mean sure you can train that too, just replace the training data with the full dataset and use `ts_alpha=0.0` and use your model of choice as the "student" and that's it I guess.

Other choices would be  [qiuqiang's](https://github.com/qiuqiangkong/audioset_tagging_cnn ).
I actually assume that you have some knowledge how to train models and such, since the teacher training part takes actually a lot of time (and requires some well equipped GPU).

> Also, I tried to process single audio file with ./src/forward.py, which returned event label and probability. Is it applicable to output frame-level prediction and time period for each sound event?

Nope this is audio tagging here, goal is to just predict the presence, without onset and offset.

**Comment by Ko-vey** [comment]
I tried to reproduce the experiment, but only gained a bad result far away from the article's...
For the Machine Annotator (MA, mobilenetv2_mAP40_53.pt), its performance on Audioset evaluation set is mAP:2.270 and Dprime:0.063.
For student model trained with MA, its performance on Audioset evaluation set is  mAP:1.710 and Dprime:0.173, which is quite far away from 35.48 and 2.588 mentioned in article.

**Comment by RicherMans** [comment]
Hey there,
seems that maybe you got some problems with your data?
Have you checked that the downloaded data is all single channel 16k?
I mean obviously, if your testing result of the teacher is not around ~40, there should be something wrong.

**Comment by Ko-vey** [comment]
Fine...I just realized that my wav files are all in a format of Sample Rate at 44100 and some are with 2 Channels...🤣
Thank you for help, anyway!
